Add --target argument to configure to allow cross-compilation.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -73,6 +73,8 @@ Option		Description				Default
 --events=...	Event handler (glib, libevent)		$events
 --ssl=...	SSL library to use (gnutls, nss, openssl, bogus, auto)
 							$ssl
+
+--target=...	Cross compilation target 		same as host
 EOF
 		exit;
 	fi
@@ -131,6 +133,13 @@ cat<<EOF>config.h
 #define CPU "$cpu"
 EOF
 
+if [ -n "$target" ]; then
+	PKG_CONFIG_PATH=/usr/$target/lib/pkgconfig
+	PATH=/usr/$target/bin:$PATH
+	CC=$target-cc
+	LD=$target-ld
+fi
+
 if [ "$debug" = "1" ]; then
 	[ -z "$CFLAGS" ] && CFLAGS=-g
 	echo 'DEBUG=1' >> Makefile.settings
@@ -157,14 +166,16 @@ fi
 
 echo "CC=$CC" >> Makefile.settings;
 
-if [ -n "$LD" ]; then
-	echo "LD=$LD" >> Makefile.settings;
-elif type ld > /dev/null 2> /dev/null; then
-	echo "LD=ld" >> Makefile.settings;
-else
-	echo 'Cannot find ld, aborting.'
-	exit 1;
+if [ -z "$LD" ]; then
+	if type ld > /dev/null 2> /dev/null; then
+		LD=ld
+	else
+		echo 'Cannot find ld, aborting.'
+		exit 1;
+	fi
 fi
+
+echo "LD=$LD" >> Makefile.settings
 
 if [ -z "$PKG_CONFIG" ]; then
 	PKG_CONFIG=pkg-config
@@ -487,6 +498,10 @@ CYGWIN* )
 	echo 'Please report any problems at http://bugs.bitlbee.org/.'
 ;;
 esac
+
+if [ -n "$target" ]; then
+	echo "Cross-compiling for: $target"
+fi
 
 echo
 echo 'Configuration done:'
