configure: address ShellCheck reports and add ShellCheck job

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,6 +7,7 @@
 ##  Copyright 2002 Lucumo   ##
 ##############################
 
+# shellcheck disable=SC2016,SC2164,SC2181
 prefix='/usr/local/'
 bindir='$prefix/bin/'
 sbindir='$prefix/sbin/'
@@ -26,7 +27,7 @@ pcdir='$prefix/lib/pkgconfig'
 systemlibdirs="/lib64 /usr/lib64 /usr/local/lib64 /lib /usr/lib /usr/local/lib"
 sysroot=''
 
-configure_args="$@"
+configure_args="$*"
 
 # Set these to default-on to let it be overriden by either the user or purple
 #
@@ -77,7 +78,7 @@ case "$arch" in
 esac
 
 get_version() {
-	REAL_BITLBEE_VERSION=$(grep '^#define BITLBEE_VERSION ' $srcdir/bitlbee.h | sed 's/.*\"\(.*\)\".*/\1/')
+	REAL_BITLBEE_VERSION=$(grep '^#define BITLBEE_VERSION ' "$srcdir/bitlbee.h" | sed 's/.*\"\(.*\)\".*/\1/')
 
 	if [ -n "$BITLBEE_VERSION" ]; then
 		# environment variable already set to something to spoof it
@@ -87,28 +88,27 @@ get_version() {
 
 	BITLBEE_VERSION=$REAL_BITLBEE_VERSION
 
-	if [ -d $srcdir/.git ] && type git > /dev/null 2> /dev/null; then
-		timestamp=$(cd $srcdir; git show -s --format=%ci HEAD | sed 's/ .*$//; s/-//g')
-		branch=$(cd $srcdir; git rev-parse --abbrev-ref HEAD)
+	if [ -d "$srcdir/.git" ] && type git > /dev/null 2> /dev/null; then
+		timestamp=$(cd "$srcdir"; git show -s --format=%ci HEAD | sed 's/ .*$//; s/-//g')
+		branch=$(cd "$srcdir"; git rev-parse --abbrev-ref HEAD)
 
 		search='\(.*\)-\([0-9]*\)-\(g[0-9a-f]*\)'
 		replace="\1+$timestamp+$branch+\2-\3-git"
 
-		describe=$(cd $srcdir; git describe --long --tags 2>/dev/null)
-		if [ $? -ne 0 ]; then
-			describe=${REAL_BITLBEE_VERSION}-0-g$(cd $srcdir; git rev-parse --short HEAD)
+		if ! (cd "$srcdir"; git describe --long --tags 2>/dev/null); then
+			describe=${REAL_BITLBEE_VERSION}-0-g$(cd "$srcdir"; git rev-parse --short HEAD)
 		fi
 
-		BITLBEE_VERSION=$(echo $describe | sed "s#$search#$replace#")
+		BITLBEE_VERSION=$(echo "$describe" | sed "s#$search#$replace#")
 
 		unset timestamp branch search replace describe
 	fi
 }
 
 if [ "$1" = "--dump-version" ]; then
-	srcdir=$(cd $(dirname $0);pwd)
+	srcdir=$(cd "$(dirname "$0")"; pwd)
 	get_version
-	echo $BITLBEE_VERSION
+	echo "$BITLBEE_VERSION"
 	exit
 fi
 
@@ -166,10 +166,10 @@ Option		Description				Default
 --target=...	Cross compilation target 		same as host
 --sysroot=...	Cross compilation sysroot 		$sysroot
 EOF
-		exit;
+		exit
 	fi
 	eval "$e"
-	shift;
+	shift
 done
 
 # Expand $prefix and get rid of double slashes
@@ -216,19 +216,21 @@ LFLAGS=
 EFLAGS=-lm
 EOF
 
-srcdir=$(cd $(dirname $0);pwd)
+srcdir=$(cd "$(dirname "$0")"; pwd)
 currdir=$(pwd)
-if [ "$srcdir" != "$currdir" ]; then 
+if [ "$srcdir" != "$currdir" ]; then
 	echo
 	echo "configure script run from a different directory. Will create some symlinks..."
-	if [ ! -e Makefile -o -L Makefile ]; then
+	if [ ! -e Makefile ] || [ -L Makefile ]; then
 		COPYDIRS="doc lib protocols tests utils"
+		# shellcheck disable=SC2046,SC2086
 		mkdir -p $(cd "$srcdir"; find $COPYDIRS -type d)
 		find . -name Makefile -type l -print0 | xargs -0 rm 2> /dev/null
 		dst="$PWD"
 		cd "$srcdir"
+		# shellcheck disable=SC2044
 		for i in $(find . -name Makefile -type f); do
-			ln -s "$PWD${i#.}" "$dst/$i";
+			ln -s "$PWD${i#.}" "$dst/$i"
 		done
 		cd "$dst"
 		rm -rf .bzr
@@ -242,7 +244,7 @@ fi
 
 cat<<EOF >config.h
 /* BitlBee settings, generated by configure
-   
+
    Do *NOT* use any of these defines in your code without thinking twice, most
    of them can/will be overridden at run-time */
 
@@ -272,15 +274,15 @@ if [ -n "$target" ]; then
 	# backward compatibility
 
 	if [ -z "$PKG_CONFIG_LIBDIR" ]; then
-		PKG_CONFIG_LIBDIR=/usr/$target/lib/pkgconfig
+		PKG_CONFIG_LIBDIR="/usr/$target/lib/pkgconfig"
 		export PKG_CONFIG_LIBDIR
 	fi
 
-	if [ -d /usr/$target/bin ]; then
-		PATH=/usr/$target/bin:$PATH
+	if [ -d "/usr/$target/bin" ]; then
+		PATH="/usr/$target/bin:$PATH"
 	fi
 
-	if [ -d /usr/$target/lib ]; then
+	if [ -d "/usr/$target/lib" ]; then
 		systemlibdirs="$systemlibdirs /usr/$target/lib"
 	fi
 
@@ -326,27 +328,27 @@ if [ "$pie" = "1" ]; then
 	echo 'LDFLAGS_BITLBEE=-pie' >> Makefile.settings
 fi
 
-echo LDFLAGS=$LDFLAGS >> Makefile.settings
-
-echo CFLAGS=$CFLAGS $CPPFLAGS >> Makefile.settings
-
-echo CFLAGS+=-DHAVE_CONFIG_H -D_GNU_SOURCE >> Makefile.settings
+cat<<EOF >>Makefile.settings
+LDFLAGS=$LDFLAGS
+CFLAGS=$CFLAGS $CPPFLAGS
+CFLAGS+=-DHAVE_CONFIG_H -D_GNU_SOURCE
+EOF
 
 if [ -n "$CC" ]; then
-	CC=$CC
+	:
 elif type gcc > /dev/null 2> /dev/null; then
 	CC=gcc
 elif type cc > /dev/null 2> /dev/null; then
 	CC=cc
 else
 	echo 'Cannot find a C compiler, aborting.'
-	exit 1;
+	exit 1
 fi
 
-echo "CC=$CC" >> Makefile.settings;
-if echo $CC | grep -qw 'gcc\|clang'; then
+echo "CC=$CC" >> Makefile.settings
+if echo "$CC" | grep -qw 'gcc\|clang'; then
 	# Apparently -Wall is gcc-specific?
-	echo CFLAGS+=-Wall -Wformat -Werror=format-security >> Makefile.settings
+	echo 'CFLAGS+=-Wall -Wformat -Werror=format-security' >> Makefile.settings
 fi
 
 if [ -z "$LD" ]; then
@@ -354,7 +356,7 @@ if [ -z "$LD" ]; then
 		LD=ld
 	else
 		echo 'Cannot find ld, aborting.'
-		exit 1;
+		exit 1
 	fi
 fi
 
@@ -378,7 +380,7 @@ CFLAGS+=$($PKG_CONFIG --cflags glib-2.0 gmodule-2.0)
 EOF
 	else
 		echo
-		echo 'Found glib2 '$($PKG_CONFIG glib-2.0 --modversion)', but version '$GLIB_MIN_VERSION' or newer is required.'
+		echo "Found glib2 $($PKG_CONFIG glib-2.0 --modversion), but version $GLIB_MIN_VERSION or newer is required."
 		exit 1
 	fi
 else
@@ -419,10 +421,12 @@ if [ "$external_json_parser" = "auto" ]; then
 fi
 echo "EXTERNAL_JSON_PARSER=$external_json_parser" >> Makefile.settings
 if [ "$external_json_parser" = "1" ]; then
-    echo "CFLAGS+=$(pkg-config --cflags json-parser)" >> Makefile.settings
-    echo "CFLAGS+=-DUSE_EXTERNAL_JSON_PARSER" >> Makefile.settings
-    echo "LDFLAGS_BITLBEE+=$(pkg-config --libs json-parser)" >> Makefile.settings
-    echo "LDFLAGS_TESTS+=$(pkg-config --libs json-parser)" >> Makefile.settings
+	cat <<EOF >>Makefile.settings
+CFLAGS+=$(pkg-config --cflags json-parser)
+CFLAGS+=-DUSE_EXTERNAL_JSON_PARSER
+LDFLAGS_BITLBEE+=$(pkg-config --libs json-parser)
+LDFLAGS_TESTS+=$(pkg-config --libs json-parser)
+EOF
 fi
 
 echo CFLAGS+=-I"${srcdir}" -I"${srcdir}"/lib -I"${srcdir}"/protocols -I. >> Makefile.settings
@@ -447,10 +451,10 @@ CFLAGS+=$(libgnutls-config --cflags) $(libgcrypt-config --cflags)
 EOF
 		
 		ssl=gnutls
-		ret=1;
+		ret=1
 	else
-		ret=0;
-	fi;
+		ret=0
+	fi
 }
 
 detect_nss()
@@ -462,17 +466,17 @@ CFLAGS+=$($PKG_CONFIG --cflags nss)
 EOF
 		
 		ssl=nss
-		ret=1;
+		ret=1
 	else
-		ret=0;
-	fi;
+		ret=0
+	fi
 }
 
 RESOLV_TESTCODE='
 #include <sys/types.h>
 #include <netinet/in.h>
 #include <arpa/nameser.h>
-#include <resolv.h> 
+#include <resolv.h>
 
 int main()
 {
@@ -486,7 +490,7 @@ RESOLV_NS_TESTCODE='
 #include <sys/types.h>
 #include <netinet/in.h>
 #include <arpa/nameser.h>
-#include <resolv.h> 
+#include <resolv.h>
 
 int main()
 {
@@ -538,13 +542,13 @@ detect_resolv_dynamic()
 	esac
 	TMPFILE=$(mktemp /tmp/bitlbee-configure.XXXXXX)
 	ret=1
-	echo "$RESOLV_TESTCODE" | $CC -o $TMPFILE -x c - $LIBRESOLV >/dev/null 2>/dev/null
+	echo "$RESOLV_TESTCODE" | $CC -o "$TMPFILE" -x c - $LIBRESOLV >/dev/null 2>/dev/null
 	if [ "$?" = "0" ]; then
 		echo "EFLAGS+=$LIBRESOLV" >> Makefile.settings
 		ret=0
 	fi
 
-	rm -f $TMPFILE
+	rm -f "$TMPFILE"
 	return $ret
 }
 
@@ -553,16 +557,16 @@ detect_resolv_static()
 	TMPFILE=$(mktemp /tmp/bitlbee-configure.XXXXXX)
 	ret=1
 	for i in $systemlibdirs; do
-		if [ -f $i/libresolv.a ]; then
-			echo "$RESOLV_TESTCODE" | $CC -o $TMPFILE -x c - -Wl,$i/libresolv.a >/dev/null 2>/dev/null
+		if [ -f "$i/libresolv.a" ]; then
+			echo "$RESOLV_TESTCODE" | $CC -o "$TMPFILE" -x c - -Wl,"$i/libresolv.a" >/dev/null 2>/dev/null
 			if [ "$?" = "0" ]; then
-				echo 'EFLAGS+='$i'/libresolv.a' >> Makefile.settings
+				echo "EFLAGS+=$i/libresolv.a" >> Makefile.settings
 				ret=0
 			fi
 		fi
 	done
 
-	rm -f $TMPFILE
+	rm -f "$TMPFILE"
 	return $ret
 }
 
@@ -577,12 +581,12 @@ detect_resolv_ns_dynamic()
 	esac
 	TMPFILE=$(mktemp /tmp/bitlbee-configure.XXXXXX)
 	ret=1
-	echo "$RESOLV_NS_TESTCODE" | $CC -o $TMPFILE -x c - $LIBRESOLV >/dev/null 2>/dev/null
+	echo "$RESOLV_NS_TESTCODE" | $CC -o "$TMPFILE" -x c - $LIBRESOLV >/dev/null 2>/dev/null
 	if [ "$?" = "0" ]; then
 		ret=0
 	fi
 
-	rm -f $TMPFILE
+	rm -f "$TMPFILE"
 	return $ret
 }
 
@@ -591,15 +595,15 @@ detect_resolv_ns_static()
 	TMPFILE=$(mktemp /tmp/bitlbee-configure.XXXXXX)
 	ret=1
 	for i in $systemlibdirs; do
-		if [ -f $i/libresolv.a ]; then
-			echo "$RESOLV_NS_TESTCODE" | $CC -o $TMPFILE -x c - -Wl,$i/libresolv.a >/dev/null 2>/dev/null
+		if [ -f "$i/libresolv.a" ]; then
+			echo "$RESOLV_NS_TESTCODE" | $CC -o "$TMPFILE" -x c - -Wl,"$i/libresolv.a" >/dev/null 2>/dev/null
 			if [ "$?" = "0" ]; then
 				ret=0
 			fi
 		fi
 	done
 
-	rm -f $TMPFILE
+	rm -f "$TMPFILE"
 	return $ret
 }
 
@@ -609,12 +613,12 @@ detect_nameser_has_ns_types()
 	ret=1
 	# since we aren't actually linking with ns_* routines
 	# we can just compile the test code
-	echo "$RESOLV_NS_TYPES_TESTCODE" | $CC -o $TMPFILE -x c -  >/dev/null 2>/dev/null
+	echo "$RESOLV_NS_TYPES_TESTCODE" | $CC -o "$TMPFILE" -x c - >/dev/null 2>/dev/null
 	if [ "$?" = "0" ]; then
 		ret=0
 	fi
 
-	rm -f $TMPFILE
+	rm -f "$TMPFILE"
 	return $ret
 }
 
@@ -622,12 +626,12 @@ detect_backtrace()
 {
 	TMPFILE=$(mktemp /tmp/bitlbee-configure.XXXXXX)
 	ret=1
-	echo "$BACKTRACE_TESTCODE" | $CC -o $TMPFILE -x c -  >/dev/null 2>/dev/null
+	echo "$BACKTRACE_TESTCODE" | $CC -o "$TMPFILE" -x c - >/dev/null 2>/dev/null
 	if [ "$?" = "0" ]; then
 		ret=0
 	fi
 
-	rm -f $TMPFILE
+	rm -f "$TMPFILE"
 	return $ret
 }
 
@@ -680,7 +684,7 @@ if [ "$ret" = "0" ]; then
 	echo '       so if you want to use that, you have to select it by hand.'
 	
 	exit 1
-fi;
+fi
 
 echo 'SSL_CLIENT=ssl_'$ssl'.o' >> Makefile.settings
 
@@ -698,7 +702,7 @@ fi
 
 if detect_backtrace; then
 	echo '#define HAVE_BACKTRACE' >> config.h
-	echo '#define CRASHFILE "'$config'crash.log"' >> config.h
+	echo '#define CRASHFILE "'"$config"'crash.log"' >> config.h
 fi
 
 STORAGES="xml"
@@ -706,7 +710,7 @@ STORAGES="xml"
 for i in $STORAGES; do
 	STORAGE_OBJS="$STORAGE_OBJS storage_$i.o"
 done
-echo "STORAGE_OBJS="$STORAGE_OBJS >> Makefile.settings
+echo "STORAGE_OBJS=$STORAGE_OBJS" >> Makefile.settings
 
 authobjs=
 authlibs=
@@ -718,8 +722,8 @@ else
 		exit 1
 	fi
 	echo '#define WITH_PAM' >> config.h
-	authobjs=$authobjs'auth_pam.o '
-	authlibs=$authlibs'-lpam '
+	authobjs="${authobjs}auth_pam.o "
+	authlibs="${authlibs}-lpam "
 fi
 if [ "$ldap" = 0 ]; then
 	echo '#undef WITH_LDAP' >> config.h
@@ -729,52 +733,52 @@ else
 		exit 1
 	fi
 	echo '#define WITH_LDAP' >> config.h
-	authobjs=$authobjs'auth_ldap.o '
-	authlibs=$authlibs'-lldap '
+	authobjs="${authobjs}auth_ldap.o "
+	authlibs="${authlibs}-lldap "
 fi
-echo AUTH_OBJS=$authobjs >> Makefile.settings
-echo EFLAGS+=$authlibs >> Makefile.settings
+echo "AUTH_OBJS=$authobjs" >> Makefile.settings
+echo "EFLAGS+=$authlibs" >> Makefile.settings
 
 if [ "$strip" = 0 ]; then
-	echo "STRIP=\# skip strip" >> Makefile.settings;
+	echo "STRIP=\# skip strip" >> Makefile.settings
 else
 	if [ "$debug" = 1 ]; then
 		echo
 		echo 'Stripping binaries does not make sense when debugging. Stripping disabled.'
 		echo 'STRIP=\# skip strip' >> Makefile.settings
-		strip=0;
+		strip=0
 	elif [ -n "$STRIP" ]; then
-		echo "STRIP=$STRIP" >> Makefile.settings;
+		echo "STRIP=$STRIP" >> Makefile.settings
 	elif type strip > /dev/null 2> /dev/null; then
-		echo "STRIP=strip" >> Makefile.settings;
+		echo "STRIP=strip" >> Makefile.settings
 	else
 		echo
 		echo 'No strip utility found, cannot remove unnecessary parts from executable.'
 		echo 'STRIP=\# skip strip' >> Makefile.settings
-		strip=0;
-	fi;
+		strip=0
+	fi
 fi
 
 if [ ! "$systemd" = "0" ]; then
-    if ! $PKG_CONFIG --exists systemd; then
-        if [ "$systemd" = "1" ]; then
-            echo "systemd requested but not found"
-            exit 1
-        else
-            systemd=0
-        fi
-    elif [ "$systemd" = "auto" ]; then
-	systemd=1
-    fi
+	if ! $PKG_CONFIG --exists systemd; then
+		if [ "$systemd" = "1" ]; then
+			echo "systemd requested but not found"
+			exit 1
+		else
+			systemd=0
+		fi
+	elif [ "$systemd" = "auto" ]; then
+		systemd=1
+	fi
 fi
 
 pkgconf_systemd_var() {
-    # First try deprecated variable, use newer variable if not found
-    if $PKG_CONFIG --print-variables systemd | grep -q "$1"; then
-        $PKG_CONFIG --variable="$1" systemd
-    else
-        $PKG_CONFIG --variable="$2" systemd
-    fi
+	# First try deprecated variable, use newer variable if not found
+	if $PKG_CONFIG --print-variables systemd | grep -q "$1"; then
+		$PKG_CONFIG --variable="$1" systemd
+	else
+		$PKG_CONFIG --variable="$2" systemd
+	fi
 }
 
 if [ "$systemd" = "1" ]; then
@@ -805,7 +809,6 @@ else
 	echo '#define WITH_PLUGINS' >> config.h
 fi
 
-otrprefix=""
 if [ "$otr" = "auto" ]; then
 	! $PKG_CONFIG --exists libotr
 	otr=$?
@@ -818,16 +821,20 @@ fi
 if [ "$otr" = 1 ]; then
 	# BI == built-in
 	echo '#define OTR_BI' >> config.h
-	echo "EFLAGS+=$($PKG_CONFIG --libs libotr) $(libgcrypt-config --libs)" >> Makefile.settings
-	echo "CFLAGS+=$($PKG_CONFIG --cflags libotr) $(libgcrypt-config --cflags)" >> Makefile.settings
-	echo 'OTR_BI=otr.o' >> Makefile.settings
+	cat <<EOF >>Makefile.settings
+EFLAGS+=$($PKG_CONFIG --libs libotr) $(libgcrypt-config --libs)
+CFLAGS+=$($PKG_CONFIG --cflags libotr) $(libgcrypt-config --cflags)
+OTR_BI=otr.o
+EOF
 elif [ "$otr" = "plugin" ]; then
 	# for some mysterious reason beyond the comprehension of my mortal mind,
 	# the libgcrypt flags aren't needed when building as plugin. add them anyway.
 	echo '#define OTR_PI' >> config.h
-	echo "OTRFLAGS=$($PKG_CONFIG --libs libotr) $(libgcrypt-config --libs)" >> Makefile.settings
-	echo "CFLAGS+=$($PKG_CONFIG --cflags libotr) $(libgcrypt-config --cflags)" >> Makefile.settings
-	echo 'OTR_PI=otr.so' >> Makefile.settings
+	cat <<EOF >>Makefile.settings
+OTRFLAGS=$($PKG_CONFIG --libs libotr) $(libgcrypt-config --libs)
+CFLAGS+=$($PKG_CONFIG --cflags libotr) $(libgcrypt-config --cflags)
+OTR_PI=otr.so
+EOF
 fi
 
 if [ -z "$PYTHON" ]; then
@@ -841,7 +848,7 @@ fi
 
 if [ "$doc" = "1" ]; then
 	# check this here just in case someone tries to install it in python2.4...
-	if [ ! -e $srcdir/doc/user-guide/help.txt ] && ! $PYTHON -m xml.etree.ElementTree > /dev/null 2>&1; then
+	if [ ! -e "$srcdir/doc/user-guide/help.txt" ] && ! $PYTHON -m xml.etree.ElementTree > /dev/null 2>&1; then
 		echo
 		echo 'ERROR: Python (>=2.5 or 3.x) is required to generate docs'
 		echo "(Use the PYTHON environment variable if it's in a weird location)"
@@ -856,7 +863,7 @@ get_version
 if [ ! "$BITLBEE_VERSION" = "$REAL_BITLBEE_VERSION" ]; then
 	echo "Spoofing version number: $BITLBEE_VERSION"
 	echo "#undef BITLBEE_VERSION" >> config.h
-	echo '#define BITLBEE_VERSION "'$BITLBEE_VERSION'"' >> config.h
+	echo '#define BITLBEE_VERSION "'"$BITLBEE_VERSION"'"' >> config.h
 	echo
 fi
 
@@ -877,6 +884,7 @@ fi
 pkgconfiglibs=''
 case "$arch" in
 CYGWIN* )
+	# shellcheck disable=SC2016
 	pkgconfiglibs='-L${libdir} -lbitlbee -no-undefined'
 esac
 
@@ -914,8 +922,8 @@ else
 	fi
 	echo '#define WITH_PURPLE' >> config.h
 	cat<<EOF >>Makefile.settings
-EFLAGS += $($PKG_CONFIG purple --libs)
-PURPLE_CFLAGS += $($PKG_CONFIG purple --cflags)
+EFLAGS+=$($PKG_CONFIG purple --libs)
+PURPLE_CFLAGS+=$($PKG_CONFIG purple --cflags)
 EOF
 	protocols=$protocols'purple '
 	protoobjs=$protoobjs'purple_mod.o '
@@ -936,9 +944,9 @@ fi
 
 case "$CC" in
 *gcc* )
-	echo CFLAGS+=-MMD -MF .depend/\$@.d >> Makefile.settings
+	echo "CFLAGS+=-MMD -MF .depend/\$@.d" >> Makefile.settings
 	for i in . lib tests protocols protocols/*/; do
-		mkdir -p $i/.depend
+		mkdir -p "$i/.depend"
 	done
 esac
 
@@ -966,7 +974,7 @@ fi
 echo "PROTOCOLS = $protocols" >> Makefile.settings
 echo "PROTOOBJS = $protoobjs" >> Makefile.settings
 
-echo Architecture: $arch
+echo "Architecture: $arch"
 case "$arch" in
 Linux )
 ;;
@@ -1048,20 +1056,20 @@ else
 	echo '  systemd disabled.'
 fi
 
-echo '  Using python: '$PYTHON
+echo "  Using python: $PYTHON"
 
 if [ "$external_json_parser" = "1" ]; then
-    echo '  Using system JSON parser.'
+	echo '  Using system JSON parser.'
 else
-    echo '  Using bundled JSON parser.'
+	echo '  Using bundled JSON parser.'
 fi
 
-echo '  Using event handler: '$events
-echo '  Using SSL library: '$ssl
+echo "  Using event handler: $events"
+echo "  Using SSL library: $ssl"
 #echo '  Building with these storage backends: '$STORAGES
 
 if [ -n "$protocols" ]; then
-	echo '  Building with these protocols:' $protocols$protocols_mods
+	echo "  Building with these protocols: $protocols$protocols_mods"
 	case "$protocols" in
 	*purple*)
 		echo "    Note that BitlBee-libpurple is supported on a best-effort basis. It's"
