configure: improve error message on missing pkg-config

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -335,7 +335,13 @@ if [ -z "$PKG_CONFIG" ]; then
 	PKG_CONFIG=pkg-config
 fi
 
-if $PKG_CONFIG --version > /dev/null 2>/dev/null && $PKG_CONFIG glib-2.0; then
+if ! $PKG_CONFIG --version > /dev/null 2>/dev/null; then
+	echo
+	echo 'Cannot find pkg-config, aborting.'
+	exit 1
+fi
+
+if $PKG_CONFIG glib-2.0; then
 	if $PKG_CONFIG glib-2.0 --atleast-version=$GLIB_MIN_VERSION; then
 		cat<<EOF >>Makefile.settings
 EFLAGS+=$($PKG_CONFIG --libs glib-2.0 gmodule-2.0)
