Systemd Enhancements: Create user and directory automatically (#163)
* configure: Simplify check for systemd, allow to request systemd support

Signed-off-by: Björn Bidar <bjorn.bidar@thaodan.de>

* configure: Add helper to be compatible with old and new systemd pc vars

Re:
https://github.com/systemd/systemd/commit/4908de44b0a0409f84a7cdc5641b114d6ce8ba03

Signed-off-by: Björn Bidar <bjorn.bidar@thaodan.de>

* systemd: Support systemd-sysusers.d

Signed-off-by: Björn Bidar <bjorn.bidar@thaodan.de>

* systemd: Define StateDirectory, create biltbee directory automatically

Signed-off-by: Björn Bidar <bjorn.bidar@thaodan.de>

* systemd: Also listen to /run/bitlbee/socket

Signed-off-by: Björn Bidar <bjorn.bidar@thaodan.de>

* systemd: Create RuntimeDirectory automatically

Signed-off-by: Björn Bidar <bjorn.bidar@thaodan.de>

* systemd: Also run regular systemd service as user

Signed-off-by: Björn Bidar <bjorn.bidar@thaodan.de>

Signed-off-by: Björn Bidar <bjorn.bidar@thaodan.de>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18,6 +18,7 @@ libdir='$prefix/lib/'
 plugindir='$prefix/lib/bitlbee/'
 includedir='$prefix/include/bitlbee/'
 systemdsystemunitdir=''
+sysusersdir=''
 libevent='/usr/'
 pidfile='/var/run/bitlbee.pid'
 ipcsocket=''
@@ -54,6 +55,8 @@ pam=0
 ldap=0
 
 pie=1
+
+systemd=auto
 
 arch=$(uname -s)
 arch_rel=$(uname -r)
@@ -128,6 +131,7 @@ Option		Description				Default
 --datadir=...						$datadir
 --plugindir=...						$plugindir
 --systemdsystemunitdir=...				$systemdsystemunitdir
+--sysusersdir                       $sysusersdir
 --pidfile=...						$pidfile
 --config=...						$config
 
@@ -156,6 +160,7 @@ Option		Description				Default
 --ssl=...	SSL library to use (gnutls, nss, openssl, auto)
 							$ssl
 --external_json_parser=0/1/auto	Use External JSON parser $external_json_parser
+--systemd=0/1  Enable/disable systemd support $systemd
 
 
 --target=...	Cross compilation target 		same as host
@@ -749,15 +754,39 @@ else
 	fi;
 fi
 
-if [ -z "$systemdsystemunitdir" ]; then
-	if $PKG_CONFIG --exists systemd; then
-		systemdsystemunitdir=$($PKG_CONFIG --variable=systemdsystemunitdir systemd)
-	fi
+if [ ! "$systemd" = 0 ]; then
+    if ! $PKG_CONFIG --exists systemd ; then
+        if [ -n "$systemdsystemunitdir" ] || [ "$systemd" -eq 1 ]; then
+            echo "systemd requested but not found"
+            exit 1
+        else
+            systemd=0
+        fi
+    fi
 fi
-if [ -n "$systemdsystemunitdir" ]; then
-	if [ "$systemdsystemunitdir" != "no" ]; then
-		echo "SYSTEMDSYSTEMUNITDIR=$systemdsystemunitdir" >> Makefile.settings
+
+pkgconf_systemd_var() {
+    # First try deprecated variable, use newer variable if not found
+    if $PKG_CONFIG --print-variables systemd | grep -q $1 ; then
+        $PKG_CONFIG --variable=$1 systemd
+    else
+        $PKG_CONFIG --variable=$2 systemd
+    fi
+}
+
+if [ "$systemd" -eq 1 ]; then
+	if [ -z "$systemdsystemunitdir" ]; then
+		systemdsystemunitdir=$(pkgconf_systemd_var systemdsystemunitdir systemd_system_unit_dir)
 	fi
+    if [ -z "$tmpfiles_dir" ] ; then
+        tmpfilesdir=$(pkgconf_systemd_var tmpfilesdir tmpfiles_dir)
+    fi
+    if [ -z "$sysusersdir" ] ; then
+        sysusersdir=$(pkgconf_systemd_var sysusersdir sysusers_dir)
+    fi
+
+	echo "SYSTEMDSYSTEMUNITDIR=$systemdsystemunitdir" >> Makefile.settings
+    echo "SYSUSERSDIR=$sysusersdir" >> Makefile.settings
 fi
 
 if [ "$gcov" = "1" ]; then
@@ -1004,7 +1033,7 @@ else
 	echo '  Off-the-Record (OTR) Messaging disabled.'
 fi
 
-if [ -n "$systemdsystemunitdir" ]; then
+if [ "$systemd" -eq 1 ]; then
 	echo '  systemd enabled.'
 else
 	echo '  systemd disabled.'
