Linux pam authentication backend
This backend authenticates users against pam.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -51,6 +51,8 @@ skype=0
 events=glib
 ssl=auto
 
+pam=0
+
 pie=1
 
 arch=$(uname -s)
@@ -132,6 +134,8 @@ Option		Description				Default
 
 --purple=0/1	Disable/enable libpurple support	$purple
 		(automatically disables other protocol modules)
+
+--pam=0/1	Disable/enable PAM authentication	$pam
 
 --doc=0/1	Disable/enable help.txt generation	$doc
 --debug=0/1	Disable/enable debugging		$debug
@@ -630,6 +634,17 @@ echo "STORAGE_OBJS="$STORAGE_OBJS >> Makefile.settings
 
 authobjs=
 authlibs=
+if [ "$pam" = 0 ]; then
+	echo '#undef WITH_PAM' >> config.h
+else
+	if ! echo '#include <security/pam_appl.h>' | $CC -E - >/dev/null 2>/dev/null; then
+		echo 'Cannot find libpam development libraries, aborting. (Install libpam0g-dev?)'
+		exit 1
+	fi
+	echo '#define WITH_PAM' >> config.h
+	authobjs=$authobjs'auth_pam.o '
+	authlibs=$authlibs'-lpam '
+fi
 echo AUTH_OBJS=$authobjs >> Makefile.settings
 echo EFLAGS+=$authlibs >> Makefile.settings
 
